version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - pip install --upgrade awscli
      - python -m unittest discover test2
      - aws lambda update-function-code --function-name=lambda-gh-action --zip-file=fileb://deploy.zip
artifacts:
  type: zip
  files:
    - '**/*'