version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - pip install --upgrade awscli
      - python -m unittest discover test2
  
  deploy:
    commands:
	    - zip -r function.zip ./
	    - aws lambda update-function-code --function-name "test2" --zip-file fileb://function.zip --region="eu-north-1" jq ".LastUpdateStatusReason" -r
	    - aws lambda wait function-updated --function-name "test2" --region="eu-north-1

artifacts:
  type: zip
  files:
    - '**/*'